### ISSUE TITLE
Either very slow or broken

### ISSUE THREAD

**Issue by Antfet** [SlippingGitty/Linux-Surface-Wizard#5]
I copied the command bash <( curl -s https://raw.githubusercontent.com/SlippingGitty/Linux-Surface-Wizard/main/SurfaceLinuxSetupWizard.sh ) into the terminal of my Ubuntu 20.10 on my Surface Pro 4. 
Now my terminal is completely blank and the CUP has been at 50% for the past 10 minutes even though I have no other programs running.
I did not see any progress and killed the frozen terminal.
Hope that did not break anything.

**Comment by SlippingGitty** [comment]
Hello there! I'm sorry that you've had a bad experience with this script. 

I was unable to reproduce the issue on either of my Surface devices (Surface Pro 3 and Surface Laptop 3/Ubuntu 20.04), at least from the steps that you have outlined. Is there any more information that you can give? Given that this is merely a simple dialog/ncurses bash script, I would *ideally* like to safely determine that this is not an issue with the script. 

I would like to redirect you to the [linux-surface Installation and Setup guide](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#debian--ubuntu) if you continue to have troubles. 

With that being said, I will continue to make any fixes necessary to insure that the Wizard is usable for everyone.

**Comment by AntonFetzer** [comment]
Sorry for my late reply.

All I did was copying that exact command into my terminal and executing it.
So that is all info I can give to reproduce the issue appart from that I am on Ubuntu 20.10 on my Surface Pro 4 with i5 and 8GB memory.
The terminal turned black and nothing happened. Then I opened the system monitor and I watched the CPU at constant 50% for 10 minutes until I figured this does not look right and killed the terminal process.

It seems like nothing broke and I haven't noticed any changes.
